# This is a basic workflow to help you get started with Actions

name: xcalscan

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Runs a set of commands using the runners shell
      - name: some testing
        run: |
          echo $HOME
          which python3
          ls
          pwd

      # install xcalagent
      - name: install xcalagent
        run: |
          wget -q https://ci-integration.oss-cn-shanghai.aliyuncs.com/xcal-agent.tgz
          tar -xf xcal-agent.tgz -C $HOME/work
          cd $HOME/work/xcal-agent/xcalbuild/linux/bear
          sudo rm -rf build
          mkdir build
          cd build
          cmake ..
          make
          sudo make install

      # install submit task
      - name: install submit task
        run: |
          wget -q https://ci-integration.oss-cn-shanghai.aliyuncs.com/submit_task.tgz
          tar -zxvf submit_task.tgz -C $HOME/work/github_action_xcalscan_cloud_integration/github_action_xcalscan_cloud_integration
          cd $HOME/work/github_action_xcalscan_cloud_integration/github_action_xcalscan_cloud_integration/install
          . ./install_submit_task.sh
          . ./set_path.sh

      # run make to build project
      - name: real build
        run: |
          cd $HOME/work/github_action_xcalscan_cloud_integration/github_action_xcalscan_cloud_integration/c_testcase/basic
          make
          echo $PYTHONPATH

      # run xcal-agent
      - name: run xcal-agent
        run: |
          export PYTHONPATH=$HOME/work/xcal-agent/agent:$HOME/work/xcal-agent/agent/commondef/src
          echo $PYTHONPATH
          cd $HOME/work/github_action_xcalscan_cloud_integration/github_action_xcalscan_cloud_integration/c_testcase/basic
          $HOME/work/xcal-agent/tools/xcal-agent.py -pc $HOME/work/github_action_xcalscan_cloud_integration/github_action_xcalscan_cloud_integration/xcal-preprocess.conf -a -d
          ls -a
          ls .xcalagent
          which submit_task.sh

      # run submit task
      - name: run submit task
        run: |
          export PATH=$PATH:$HOME/github_action_xcalscan_cloud_integration/github_action_xcalscan_cloud_integration/bin
          echo $PATH
          cd $HOME/work/github_action_xcalscan_cloud_integration/github_action_xcalscan_cloud_integration/c_testcase/basic
          cd "$(dirname "$(find . -type f -name xcal-task.conf | head -1)")"
          before_submit.sh
          ls
          cat xcal-task.conf
          submit_task.sh xcal-task.conf

